import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode}) 
  {
    return  (
    <>
    <main>
        child layout 
        {children}
    </main>
    </>
  )
}
